[package]
name = "unreal-rs"
version = "0.1.0"
edition = "2021"
description = "Unreal Engine Rust Integration"
license = "Apache-2.0"
documentation = "https://docs.rs/unreal-rs"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
